live_config_reload = true
window.opacity = 0.97

import = [
  # uncomment the flavour you want below:
  #"~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
   "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 14
normal.family = "JetBrainsMono Nerd Font"
normal.style = "SemiBold"
italic.family = "JetBrainsMono Nerd Font"
italic.style = "SemiBold Italic"
#glyph_offset.y = -1
offset.y = -1
#builtin_box_drawing = false

[window.padding]
x = 9
y = 15

[window.dimensions]
#columns = 174
#lines = 40
columns = 160
lines = 36


[colors]
draw_bold_text_with_bright_colors = true
#transparent_background_colors = true
