live_config_reload = true
window.opacity = 0.93

import = [
  # uncomment the flavour you want below:
  #"~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
   "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 13
normal.family = "JetBrainsMono Nerd Font"
normal.style = "Medium"

[shell]
program = "/usr/bin/fish"

[window.padding]
x = 9
y = 12

[window.dimensions]
columns = 175
lines = 38

[env]
TERM = "xterm-256color"


[colors]
transparent_background_colors = true
